name: flutter_engineer_codecheck
description: A new Flutter project.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  retrofit: ^4.0.3
  flutter_dotenv: ^5.1.0
  github_language_colors: ^1.0.1
  go_router: ^12.1.1
  flutter_markdown: ^0.6.18+2
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  pedantic_mono: any
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.3
  mocktail: ^1.0.1
  golden_toolkit: ^0.15.0
  mocktail_image_network: ^1.0.0
  go_router_builder: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - .env
  generate: true
